apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caas-privatebin
  namespace: argocd
  labels:
    caas.app.type: Infra
    caas.app.name: PrivateBin
spec:
  project: caas-infra
  source:
    repoURL: 'https://privatebin.github.io/helm-chart/'
    chart: privatebin
    targetRevision: 0.15.0
    helm:
      values: |
        additionalLabels: {}
        affinity: {}
        configs:
          conf.php: |-
            [main]
            name = "AssoCocktail - PrivateBin"
            discussion = true
            opendiscussion = false
            password = true
            fileupload = true
            burnafterreadingselected = true
            defaultformatter = "plaintext"
            sizelimit = 10485760
            template = "bootstrap-dark"
            languageselection = true
            qrcode = true

            [expire]
            default = "1week"

            [expire_options]
            5min = 300
            10min = 600
            1hour = 3600
            1day = 86400
            1week = 604800
            1month = 2592000
            1year = 31536000
            never = 0

            [formatter_options]
            plaintext = "Plain Text"
            syntaxhighlighting = "Source Code"
            markdown = "Markdown"

            [traffic]
            limit = 10

            [purge]
            limit = 300
            batchsize = 10

            [model]
            class = Filesystem

            [model_options]
            dir = PATH "data"
        controller:
          emptyDir: null
          kind: Deployment
          pvc:
            accessModes: ReadWriteOnce
            requests: 1Gi
        datapath: /srv/data
        fullnameOverride: ''
        image:
          pullPolicy: IfNotPresent
          repository: privatebin/nginx-fpm-alpine
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/tls-acme: "true"
          enabled: true
          hosts:
            - host: privatebin.priv.asso-cocktail.org
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - privatebin.priv.asso-cocktail.org
              secretName: privatebin.priv.asso-cocktail.org-tls
        nameOverride: ''
        nodeSelector: {}
        podAnnotations: {}
        podSecurityPolicy:
          annotations: []
          enabled: false
        rbac:
          create: false
          serviceAccount:
            annotations: {}
            name: ''
        replicaCount: 1
        resources: {}
        securityContext:
          fsGroup: 82
          runAsGroup: 82
          runAsUser: 65534
        service:
          annotations: {}
          port: 80
          portName: http
          type: ClusterIP
        tolerations: []
  destination:
    namespace: privatebin
    name: Tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true