apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caas-adherent6-gfc-services
  namespace: argocd
  labels:
    caas.app.type: SpringBoot
    caas.app.name: gfc-services
spec:
  project: caas-applications
  source:
    repoURL: 'git@forge.in.asso-cocktail.org:dsiadm/caas/caas-helm-charts.git'
    path: charts/caas-springboot
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - adherent6/common-values.yaml
        - adherent6/gfc-services-values.yaml
  destination:
    namespace: adherent6
    name: Dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true